services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: mta-api
    labels:
      ip_offset: "20"
    restart: unless-stopped
