services:
  analyst:
    mem_limit: 1g
    cpus: 1.0
    build:
      context: ./containers/analyst
      dockerfile: Dockerfile
    hostname: avalon-soc
    labels:
      ip_offset: "26"
    restart: unless-stopped
