services:
  server-alpha:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/server-alpha
      dockerfile: Dockerfile
    hostname: titan-alpha
    labels:
      ip_offset: "11"
    restart: unless-stopped

  server-bravo:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/server-bravo
      dockerfile: Dockerfile
    hostname: titan-bravo
    labels:
      ip_offset: "27"
    restart: unless-stopped

  server-charlie:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/server-charlie
      dockerfile: Dockerfile
    hostname: titan-charlie
    labels:
      ip_offset: "41"
    restart: unless-stopped

  server-delta:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/server-delta
      dockerfile: Dockerfile
    hostname: titan-delta
    labels:
      ip_offset: "55"
    restart: unless-stopped
