services:
  webportal:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webportal
      dockerfile: Dockerfile
    hostname: financecorp-web
    labels:
      ip_offset: "10"
    restart: unless-stopped

  fileserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/fileserver
      dockerfile: Dockerfile
    hostname: financecorp-fs
    labels:
      ip_offset: "20"
    restart: unless-stopped

  dc:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/dc
      dockerfile: Dockerfile
    hostname: financecorp-dc
    labels:
      ip_offset: "30"
    restart: unless-stopped
