services:
  branch-fs:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/branch-fs
      dockerfile: Dockerfile
    hostname: atlas-ccx-fs01
    labels:
      ip_offset: "10"
    restart: unless-stopped

  branch-portal:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/branch-portal
      dockerfile: Dockerfile
    hostname: atlas-ccx-portal
    labels:
      ip_offset: "11"
    restart: unless-stopped
