services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: truenorth-web
    labels:
      ip_offset: "22"
    restart: unless-stopped
