services:
  host-a:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/host-a
      dockerfile: Dockerfile
    hostname: meridian-teller
    labels:
      ip_offset: "15"
    restart: unless-stopped

  host-b:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/host-b
      dockerfile: Dockerfile
    hostname: meridian-appsvr
    labels:
      ip_offset: "32"
    restart: unless-stopped

  host-c:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/host-c
      dockerfile: Dockerfile
    hostname: meridian-core
    labels:
      ip_offset: "48"
    restart: unless-stopped
