services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: blackrock-srv01
    labels:
      ip_offset: "31"
    restart: unless-stopped
