services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: sb-api
    labels:
      ip_offset: "18"
    restart: unless-stopped
    depends_on:
      - dbserver

  dbserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/dbserver
      dockerfile: Dockerfile
    hostname: sb-db
    labels:
      ip_offset: "39"
    restart: unless-stopped
