services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: ironforge-host01
    labels:
      ip_offset: "25"
    restart: unless-stopped
