services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: cascade-platform
    labels:
      ip_offset: "21"
    restart: unless-stopped
