services:
  analyst-workstation:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: medicare-analyzer
    labels:
      ip_offset: "10"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
