services:
  workstation:
    mem_limit: 1g
    cpus: 1.0
    build:
      context: ./containers/workstation
      dockerfile: Dockerfile
    hostname: cv-analyst-ws
    labels:
      ip_offset: "29"
    restart: unless-stopped
