services:
  kestrel-portal:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/kestrel-portal
      dockerfile: Dockerfile
    hostname: kestrel-cms
    labels:
      ip_offset: "10"
    restart: unless-stopped

  kestrel-fs:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/kestrel-fs
      dockerfile: Dockerfile
    hostname: kestrel-fs01
    labels:
      ip_offset: "11"
    restart: unless-stopped
