services:
  analyst:
    mem_limit: 1g
    cpus: 1.0
    build:
      context: ./containers/analyst
      dockerfile: Dockerfile
    hostname: horizon-soc
    labels:
      ip_offset: "29"
    restart: unless-stopped
