services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: vertex-web
    labels:
      ip_offset: "16"
    restart: unless-stopped
    depends_on:
      - dbserver

  dbserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/dbserver
      dockerfile: Dockerfile
    hostname: vertex-db
    labels:
      ip_offset: "37"
    restart: unless-stopped
