services:
  webserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webserver
      dockerfile: Dockerfile
    hostname: crestline-web
    labels:
      ip_offset: "12"
    restart: unless-stopped

  dbserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/dbserver
      dockerfile: Dockerfile
    hostname: crestline-db
    labels:
      ip_offset: "34"
    restart: unless-stopped
