services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: orion-svr01
    labels:
      ip_offset: "15"
    restart: unless-stopped
