services:
  target-alpha:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target-alpha
      dockerfile: Dockerfile
    hostname: dmz-alpha
    labels:
      ip_offset: "14"
    restart: unless-stopped

  target-bravo:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target-bravo
      dockerfile: Dockerfile
    hostname: dmz-bravo
    labels:
      ip_offset: "29"
    restart: unless-stopped

  target-charlie:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target-charlie
      dockerfile: Dockerfile
    hostname: dmz-charlie
    labels:
      ip_offset: "43"
    restart: unless-stopped
