services:
  target:
    image: linux-1-4-non-standard-port-discovery-target:latest
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: techstart-nonstandard
    labels:
      ip_offset: "10"
    ports:
      - "34567:34567"
      - "22222:22222"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
