services:
  webfront:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webfront
      dockerfile: Dockerfile
    hostname: zenith-web
    labels:
      ip_offset: "10"
    restart: unless-stopped

  appserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/appserver
      dockerfile: Dockerfile
    hostname: zenith-app
    labels:
      ip_offset: "24"
    restart: unless-stopped

  datastore:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/datastore
      dockerfile: Dockerfile
    hostname: zenith-db
    labels:
      ip_offset: "42"
    restart: unless-stopped
