services:
  perimeter:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/perimeter
      dockerfile: Dockerfile
    hostname: nexus-web
    labels:
      ip_offset: "11"
    restart: unless-stopped

  core:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/core
      dockerfile: Dockerfile
    hostname: nexus-core
    labels:
      ip_offset: "36"
    restart: unless-stopped
