services:
  network-2-5:
    mem_limit: 512m
    cpus: 0.5
    build: .
    hostname: medicare-analyzer
    labels:
      ip_offset: "10"
    stdin_open: true
    tty: true
    restart: unless-stopped
