services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: pinnacle-docs
    labels:
      ip_offset: "16"
    restart: unless-stopped
