services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: medcore-web
    labels:
      ip_offset: "18"
    restart: unless-stopped
    depends_on:
      - dbserver

  dbserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/dbserver
      dockerfile: Dockerfile
    hostname: medcore-db
    labels:
      ip_offset: "39"
    restart: unless-stopped

  internal:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/internal
      dockerfile: Dockerfile
    hostname: medcore-proc
    labels:
      ip_offset: "52"
    restart: unless-stopped
