services:
  webserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webserver
      dockerfile: Dockerfile
    hostname: meridian-intranet
    labels:
      ip_offset: "18"
    restart: unless-stopped

  dbserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/dbserver
      dockerfile: Dockerfile
    hostname: meridian-db
    labels:
      ip_offset: "41"
    restart: unless-stopped
