services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: hargrove-fs01
    labels:
      ip_offset: "27"
    restart: unless-stopped
