services:
  dns-server:
    build:
      context: ./containers/dns-server
      dockerfile: Dockerfile
    hostname: medicare-dns
    labels:
      ip_offset: "10"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
