
services:
  target1:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target1
      dockerfile: Dockerfile
    hostname: windows-target1
    labels:
      ip_offset: "10"
    restart: unless-stopped

  target2:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target2
      dockerfile: Dockerfile
    hostname: windows-target2
    labels:
      ip_offset: "20"
    restart: unless-stopped

  target3:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target3
      dockerfile: Dockerfile
    hostname: windows-target3
    labels:
      ip_offset: "30"
    restart: unless-stopped

