services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: obsidian-analytics
    labels:
      ip_offset: "26"
    restart: unless-stopped
