
services:
  webserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webserver
      dockerfile: Dockerfile
    hostname: main-webserver
    labels:
      ip_offset: "127"
    restart: unless-stopped

  admin:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/admin
      dockerfile: Dockerfile
    hostname: admin-webserver
    labels:
      ip_offset: "131"
    restart: unless-stopped

  api:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/api
      dockerfile: Dockerfile
    hostname: api-webserver
    labels:
      ip_offset: "137"
    restart: unless-stopped

