services:
  portal:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/portal
      dockerfile: Dockerfile
    hostname: pinnacle-web
    labels:
      ip_offset: "17"
    restart: unless-stopped

  docserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/docserver
      dockerfile: Dockerfile
    hostname: pinnacle-docs
    labels:
      ip_offset: "43"
    restart: unless-stopped

  casemgmt:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/casemgmt
      dockerfile: Dockerfile
    hostname: pinnacle-case
    labels:
      ip_offset: "89"
    restart: unless-stopped
