services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: meridian-build01
    labels:
      ip_offset: "19"
    restart: unless-stopped
