
services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: windows-target
    labels:
      ip_offset: "10"
    restart: unless-stopped

