services:
  analyst-workstation:
    build:
      context: ./containers/analyst-workstation
      dockerfile: Dockerfile
    hostname: medicare-analyst
    labels:
      ip_offset: "10"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
