services:
  webapp:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webapp
      dockerfile: Dockerfile
    hostname: novatech-web
    labels:
      ip_offset: "23"
    restart: unless-stopped
    depends_on:
      - dbserver

  dbserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/dbserver
      dockerfile: Dockerfile
    hostname: novatech-db
    labels:
      ip_offset: "41"
    restart: unless-stopped
