
services:
  webserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webserver
      dockerfile: Dockerfile
    hostname: recon-webserver
    labels:
      ip_offset: "17"
    restart: unless-stopped

