services:
  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: ridgeline-gw01
    labels:
      ip_offset: "33"
    restart: unless-stopped
