services:
  attacker:
    mem_limit: 1g
    cpus: 1.0
    build:
      context: ./containers/attacker
      dockerfile: Dockerfile
    hostname: threat-actor
    labels:
      ip_offset: "31"
    restart: unless-stopped
    depends_on:
      - analyst
      - target

  target:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/target
      dockerfile: Dockerfile
    hostname: sentinel-portal
    labels:
      ip_offset: "17"
    restart: unless-stopped

  analyst:
    mem_limit: 1g
    cpus: 1.0
    build:
      context: ./containers/analyst
      dockerfile: Dockerfile
    hostname: ids-sensor
    labels:
      ip_offset: "47"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    restart: unless-stopped
