
services:
  webserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webserver
      dockerfile: Dockerfile
    hostname: secure-webserver
    labels:
      ip_offset: "89"
    restart: unless-stopped

