services:
  webserver:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/webserver
      dockerfile: Dockerfile
    hostname: apex-web
    labels:
      ip_offset: "13"
    restart: unless-stopped

  backend:
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ./containers/backend
      dockerfile: Dockerfile
    hostname: apex-backend
    labels:
      ip_offset: "38"
    restart: unless-stopped
