#!/usr/bin/env bash
# deploy-wiki.sh - build the wiki content tree from the manifest, bake it into
# the frontend image, redeploy, and verify.
#
# Single source of truth:
#   tracks:   wikis.yaml                  -> /wiki/range/<slug>/
#   courses:  tools/wiki-gen/courses.json -> /wiki/course/<slug>/
#   index:    generated by tools/wiki-gen -> /wiki/
#
# Usage:
#   deploy-wiki.sh list      show the planned routing table
#   deploy-wiki.sh build     build the namespaced wiki tree into the frontend context
#   deploy-wiki.sh deploy    build + rebuild the frontend image + recreate + verify
set -euo pipefail

# Default to the tree this script lives in rather than one developer's home
# directory. Both stay overridable, which is what the split between a source
# repo and a separate build context needs; hardcoding the author's paths only
# meant every other install had to override them, and it published those paths
# in the release.
DEV_REPO="${DEV_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
DESKTOP="${DESKTOP:-$DEV_REPO}"
FRONTEND="${FRONTEND:-$DESKTOP/platform/frontend}"
GEN="$DEV_REPO/tools/wiki-gen"
PLAN="$(mktemp)"
trap 'rm -f "$PLAN"' EXIT

build_tree() {
  echo "[*] regenerating artifacts from wikis.yaml"
  python3 "$GEN/generate.py" emit --out "$GEN/generated" >/dev/null

  echo "[*] planning builds (tracks + courses)"
  python3 - "$DEV_REPO" > "$PLAN" <<'PY'
import yaml, json, sys
repo = sys.argv[1]
m = yaml.safe_load(open(f"{repo}/wikis.yaml"))
rows = [("range", s, t["config"]) for s, t in m.get("tracks", {}).items()]
rows += [("reference", s, r["config"]) for s, r in m.get("reference", {}).items() if r.get("config")]
rows += [("course", c["slug"], c["config"])
         for c in json.load(open(f"{repo}/tools/wiki-gen/courses.json")) if c.get("config")]
print("\n".join("\t".join(r) for r in rows))
PY

  echo "[*] building namespaced tree"
  rm -rf "$FRONTEND/wiki.new"
  mkdir -p "$FRONTEND/wiki.new/range" "$FRONTEND/wiki.new/course" "$FRONTEND/wiki.new/reference"
  while IFS=$'\t' read -r ns slug config; do
    [ -z "${ns:-}" ] && continue
    echo "    build $ns/$slug ($config)"
    ( cd "$DEV_REPO" && mkdocs build -f "$config" --site-dir "$FRONTEND/wiki.new/$ns/$slug" --clean ) \
      >/dev/null 2>&1 || { echo "    BUILD FAILED: $config"; return 1; }
  done < "$PLAN"

  cp "$GEN/generated/index.html" "$FRONTEND/wiki.new/index.html"

  rm -rf "$FRONTEND/wiki.prev"
  [ -d "$FRONTEND/wiki" ] && mv "$FRONTEND/wiki" "$FRONTEND/wiki.prev"
  mv "$FRONTEND/wiki.new" "$FRONTEND/wiki"
  echo "[*] tree ready: range=$(ls "$FRONTEND/wiki/range" | wc -l) reference=$(ls "$FRONTEND/wiki/reference" | wc -l) course=$(ls "$FRONTEND/wiki/course" | wc -l)"

  # Refuse to bake an image the database already disagrees with. A course whose
  # wiki_slug has no built output 404s for every enrolled student, and nothing
  # downstream notices: the auth gate answers before nginx looks for the file,
  # so an unauthenticated probe cannot tell missing from gated.
  #
  # Advisory when the database cannot be reached, because building a wiki tree
  # on a machine with no platform database is a normal thing to do.
  if [ -n "${SKIP_WIKI_COVERAGE:-}" ]; then
    echo "[*] wiki coverage check skipped (SKIP_WIKI_COVERAGE set)"
  else
    echo "[*] checking course coverage against the database"
    if ! python3 "$GEN/check_wiki_coverage.py" \
         --build-context "$FRONTEND" \
         --courses-json "$GEN/courses.json" \
         --psql "${WIKI_COVERAGE_PSQL:-docker exec ocr-db psql -U labuser -d labdb}"; then
      echo "    Refusing to build the image. Fix the gap above, or set"
      echo "    SKIP_WIKI_COVERAGE=1 if you know this deployment serves those"
      echo "    courses from somewhere else."
      return 1
    fi
  fi
}

case "${1:-deploy}" in
  list)
    python3 "$GEN/generate.py" summary
    ;;
  build)
    build_tree
    ;;
  deploy)
    build_tree
    echo "[*] rebuilding + recreating frontend"
    ( cd "$DESKTOP" && docker compose build frontend && docker compose up -d frontend )
    sleep 4
    echo "[*] nginx config test:"
    docker exec ocr-frontend nginx -t
    echo "[*] done. Run tools/wiki-gen/wiki_doctor.py to verify routes."
    ;;
  *)
    echo "usage: deploy-wiki.sh [list|build|deploy]" >&2
    exit 1
    ;;
esac
